apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mynode-exporter
  labels:
    app: mynode-exporter
spec:
  selector:
    matchLabels:
      app: mynode-exporter
  template:
    metadata:
      labels:
        app: mynode-exporter
    spec:
       containers:
          - name: mynode-exporter
            image: prom/node-exporter:v0.18.1
            ports:
              - containerPort: 9100
                hostPort: 9100
                protocol: TCP

