apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    webserver: httpd
  type: NodePort 
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32004
    

---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    webserver: httpd
spec:
  containers:
  - name: cont1
    image: httpd
    ports:
      - containerPort: 80
  - name: cont2
    image: jenkins/jenkins

    ports:
      - containerPort: 8080

       
